import {by, element, until} from "protractor";
export const assetbookElement: any = {
    loginPage: {
        loginTextLogo: element(by.css('.login__pulse-image--side-panel')),
        loginLogo: element(by.css('.login__background__logo')),
        loginText: element(by.css('.login__text--large')),
        userNameInput: element(by.css('#username')),
        userNameInputLabel: element(by.css('#username__label')),
        passwordInput: element(by.css('#password')),
        passwordInputLabel: element(by.css('.login__text--mediumgray')),
        eyeIcon: element(by.css('.login__eye-icon--gray')),
        resetPasswordLink: element(by.css('.login__anchor')),
        enabledLoginButton: element(by.css('.login__button')),
        disabledLoginButton: element.all(by.xpath('//div/div[2]/div/section/div[4]/div')).first(),
        loginErrorMessage: element.all(by.css('.login__text-red')).first()
    },

    dbPage: {
        SDFinancial: element(by.xpath('//div/main/section/impersonate-search-result[12]/div[1]/header/span'))
    },

    header: {
        logo: element(by.xpath('//img[@src="/05c3211b84169083c7dfc1587edce9a9.svg"]')),
        mainMenuIcon: element(by.css('i[class="fa fa-bars navicon"]')),
        searchField: element(by.css('#ab-search')),
        userLabel: element(by.xpath('//div[@class="nav-bar__user-panel"]//span[@class="user-panel__user-first-later"][contains(text(),"DS")]'))
    },

    search: {
        resultItem: element(by.xpath('/html/body/nav-bar/section/section[2]/section[1]/search/div[2]/section/section[2]/div[2]/div[1]/div[2]/div[1]/div[1]')),
        xButton: element(by.xpath('/html/body/nav-bar/section/section[2]/section[1]/search/div[2]/section/div[1]/span[2]/img'))
    },

    dashboardPage: {
        assetsUnderManagementChart: element(by.css('#myChart')),
        top4HouseholdsChart: element(by.css('#topHouseholdsChart'))
    },

    mainMenu: {
        dashboardItem: element(by.css('a[data-text="Dashboard"]')),
        householdsItem: element(by.css('a[data-text="Households"]')),
        accountsItem: element(by.css('a[data-text="Accounts"]')),
        investmentsItem: element(by.css('a[data-text="Investments"]')),
        reportsItem: element(by.css('a[data-text="Reports"]')),
        documentCenterItem: element(by.css('a[data-text="Document Center"]'))
    },

    households: {
        viewDropdown: element(by.css('i[class="fa fa-chevron-down ab-custom-view__arrow"]')),
        viewDropdownName: element(by.css('p[class="ab-custom-view__dropdown__view__name au-target"]')),
        viewDropdownItem: element(by.css('div[title="1DmitryView"]')),
        householdsGrid: element(by.css('div[data-role="grid"]')),
        columnMarketValue: element(by.xpath('//a[text()="Market Value"]')),
        columnTradeDate: element(by.xpath('//a[text()="Trade Date"]')),
        ascArrow: element(by.css('span[class="k-icon k-i-sort-asc-sm"]')),
        descArrow: element(by.css('span[class="k-icon k-i-sort-desc-sm"]')),
        addNewHouseholdButton: element(by.xpath('//button[@value="undefined"]')),
        addNewHouseholdPageTitle: element(by.css('div[class="edit-household__title"]')),
        householdNameInput: element(by.css('input[name="householdName"]')),
        reportingNameInput: element(by.css('input[name="reportingName"]')),
        addButton: element(by.xpath('//div[@class="edit__household__wrapper__buttons"]//button[@value="undefined"][contains(text(),"Add")]')),
        householdItem: element(by.xpath('//div[@class="k-grid-content k-auto-scrollable"]//tr[1]')),
        gearIcon: element(by.xpath('//i[@class="au-target entity__settings__gear fa fa-cog"]')),
        overviewTab: element(by.xpath('//label[text()="Overview"]')),
        performanceTab: element(by.xpath('//label[text()="Performance"]')),
        activityTab: element(by.xpath('//label[text()="Activity"]')),
        taxTab: element(by.xpath('//label[text()="Tax"]')),
        positionsTab: element(by.xpath('//label[text()="Positions"]')),
        accountsTab: element(by.xpath('//label[text()="Accounts"]')),
        saveButton: element(by.css('body.ux-dialog-open:nth-child(2) ux-dialog-container.active:nth-child(2) div.edit-household__container div.edit-household__small-container div.edit-household__container-first div.edit__household__wrapper__buttons:nth-child(4) ab-button.au-target > button.au-target.ab-button-medium.ab-button-primary')),
        activeStatus: element(by.xpath('//label[@class="household-settings__checkbox-label"]')),
        entityDropdown: element(by.xpath('//div[@class="au-target entity__selection__dropdown__title"]')),
        entityDropdownLabel: element(by.xpath('//div[@class="entity__selection__dropdown__title__wrapper"]')),
        entityAccountList: element(by.xpath('//div[@class="entity__selection__account__list"]/div[@class="au-target"]')),
        entityAccountItem: element(by.xpath('(//li[@class="au-target entity__dropdown__item"])[1]')),
        activityGrid: element(by.xpath('//div[@class="k-widget k-grid k-display-block"]')),
        transactionSaveChangesButton: element(by.xpath('//button[contains(text(),"Save Changes")]')),
        performanceChart: element(by.xpath('//*[@class="highcharts-root"]')),
        addTransactionButton: element(by.xpath('//button[@value="undefined"]')),
        buysTab: element(by.xpath('//div[@class="entity-activity__category-menu"]//div[2]//div[1]')),
        totalAmount: element(by.xpath('//div[@id="AGG_dollars"]')),
        buysLabel: element(by.xpath('//label[@class="entity-activity__button-label"]')),
        actionDropdown: element(by.css('div[class="ab-dropdown__dropdown"]:nth-child(1)')),
        actionDropdownItem: element(by.xpath('//section[@class="au-target content__wrapper"]//li[6]//label')),
        symbolInput: element(by.xpath('//input[@class="symbol-lookup__input au-target"]')),
        symbolInputItem: element(by.xpath('(//div[@class="symbol-lookup__dropdown-row au-target"][1])')),
        quantityInput: element(by.xpath('//input[2]')),
        dollarsInput: element(by.xpath('//input[3]')),
        priceInput: element(by.xpath('//input[4]')),
        saveChangesButton: element(by.xpath('//button[contains(text(),"Save Changes")]')),
        activityItem: element(by.xpath('//td[contains(text(),"SSE")]')),
        activityDetailsLabel: element(by.xpath('//div[@class="transaction__screen-left-header"]')),
        activityElem: element(by.xpath('//div[@class="k-grid-content k-auto-scrollable"]//tr[1]')),
        positionDropdown: element(by.xpath('//div[@class="au-target searchable-dropdown__header-container"]')),
        positionDropdownItem: element(by.xpath('(//div[@class="searchable-dropdown__data-row au-target"])[3]')),
        saveActivityButton: element(by.xpath('//button[contains(text(),"Save")]')),
        deleteActivityButton: element(by.xpath('//button[contains(text(),"Delete Activity")]')),
        deleteDialogInput: element(by.xpath('//input[@class="dialog-message__input au-target"]')),
        deleteDialogYesButton: element(by.xpath('//button[contains(text(),"Yes, I want to delete it")]')),
        columnDateSold: element(by.xpath('//a[text()="Date Sold"]')),
        unrealizedTab: element(by.xpath('//li[@class="au-target household-tax__header__menu__item"]')),
        realizedTab: element(by.xpath('//li[@class="au-target household-tax__header__menu__item"]')),
        yearDropdown: element(by.xpath('//div[@class="ab-dropdown__dropdown"]')),
        positionsGrid: element(by.xpath('//div[@class="k-grid k-widget k-display-block"]')),
        positionElem: element(by.xpath('//div[@class="k-grid-content k-auto-scrollable"]//tr[1]')),
        positionDetailsLabel: element(by.xpath('//div[@class="position-details__title"]')),
        taxMethodDropdown: element(by.xpath('//div[3]//ab-dropdown[1]')),
        taxMethodDropdownItem: element(by.xpath('//div[@class="ab-dropdown__content au-target"]//li[2]')),
        savePositionButton: element(by.xpath('//button[contains(text(),"Save")]')),
    },

    accounts: {
        viewDropdown: element(by.css('i[class="fa fa-chevron-down ab-custom-view__arrow"]')),
        viewDropdownName: element(by.css('p[class="ab-custom-view__dropdown__view__name au-target"]')),
        viewDropdownItem: element(by.css('div[title="1DmitryView"]')),
        householdsGrid: element(by.css('div[data-role="grid"]')),
        columnMarketValue: element(by.xpath('//a[text()="Market Value"]')),
        columnTradeDate: element(by.xpath('//a[text()="Trade Date"]')),
        ascArrow: element(by.css('span[class="k-icon k-i-sort-asc-sm"]')),
        descArrow: element(by.css('span[class="k-icon k-i-sort-desc-sm"]')),
        addNewAccountButton: element(by.xpath('//button[@value="undefined"]')),
        householdsDropdown: element(by.xpath('//div[@class="au-target searchable-dropdown__header-container"]')),
        householdsDropdownItem: element(by.xpath('//div[contains(text(),"AFWuqmgu, Kdpfge S.")]')),
        registrationInput: element(by.xpath('//div[@class="edit-account__row"]//div[2]//input[1]')),
        accountNumberInput: element(by.xpath('//input[@name="accountNumber"]')),
        accountTypeDropdown: element(by.xpath('//div[@class="edit-account__row"]//div[2]//div[1]//ab-dropdown[1]')),
        accountTypeDropdownItem: element(by.xpath('//div[@class="ab-dropdown__content au-target"]//li[4]')),
        saveNewAccountButton: element(by.xpath('//div[@class="edit-account__button__wrapper"]//button[@value="undefined"][contains(text(),"Add")]')),
        addNewHouseholdPageTitle: element(by.css('div[class="edit-household__title"]')),
        addButton: element(by.xpath('//div[@class="edit__household__wrapper__buttons"]//button[@value="undefined"][contains(text(),"Add")]')),
        accountItem: element(by.xpath('//div[@class="k-grid-content k-auto-scrollable"]//tr[1]')),
        gearIcon: element(by.xpath('//i[@class="au-target entity__settings__gear fa fa-cog"]')),
        overviewTab: element(by.xpath('//label[text()="Overview"]')),
        performanceTab: element(by.xpath('//label[text()="Performance"]')),
        activityTab: element(by.xpath('//label[text()="Activity"]')),
        taxTab: element(by.xpath('//label[text()="Tax"]')),
        positionsTab: element(by.xpath('//label[text()="Positions"]')),
        accountsTab: element(by.xpath('//label[text()="Accounts"]')),
        saveButton: element(by.css('body.ux-dialog-open:nth-child(2) ux-dialog-container.active:nth-child(2) div.edit-household__container div.edit-household__small-container div.edit-household__container-first div.edit__household__wrapper__buttons:nth-child(4) ab-button.au-target > button.au-target.ab-button-medium.ab-button-primary')),
        activeStatus: element(by.xpath('//label[@class="household-settings__checkbox-label"]')),
        entityDropdown: element(by.xpath('//div[@class="au-target entity__selection__dropdown__title"]')),
        entityDropdownLabel: element(by.xpath('//div[@class="entity__selection__dropdown__title__wrapper"]')),
        entityAccountList: element(by.xpath('//div[@class="entity__selection__account__list"]/div[@class="au-target"]')),
        entityAccountItem: element(by.xpath('(//li[@class="au-target entity__dropdown__item"])[1]')),
        activityGrid: element(by.xpath('//div[@class="k-widget k-grid k-display-block"]')),
        transactionSaveChangesButton: element(by.xpath('//button[contains(text(),"Save Changes")]')),
        performanceChart: element(by.xpath('//*[@class="highcharts-root"]')),
        addTransactionButton: element(by.xpath('//button[@value="undefined"]')),
        buysTab: element(by.xpath('//div[@class="entity-activity__category-menu"]//div[2]//div[1]')),
        totalAmount: element(by.xpath('//div[@id="AGG_dollars"]')),
        buysLabel: element(by.xpath('//label[@class="entity-activity__button-label"]')),
        actionDropdown: element(by.css('div[class="ab-dropdown__dropdown"]:nth-child(1)')),
        actionDropdownItem: element(by.xpath('//section[@class="au-target content__wrapper"]//li[6]//label')),
        symbolInput: element(by.xpath('//input[@class="symbol-lookup__input au-target"]')),
        symbolInputItem: element(by.xpath('(//div[@class="symbol-lookup__dropdown-row au-target"][1])')),
        quantityInput: element(by.xpath('//input[2]')),
        dollarsInput: element(by.xpath('//input[3]')),
        priceInput: element(by.xpath('//input[4]')),
        saveChangesButton: element(by.xpath('//button[contains(text(),"Save Changes")]')),
        activityItem: element(by.xpath('//td[contains(text(),"SSE")]')),
        activityDetailsLabel: element(by.xpath('//div[@class="transaction__screen-left-header"]')),
        activityElem: element(by.xpath('//div[@class="k-grid-content k-auto-scrollable"]//tr[1]')),
        positionDropdown: element(by.xpath('//div[@class="au-target searchable-dropdown__header-container"]')),
        positionDropdownItem: element(by.xpath('(//div[@class="searchable-dropdown__data-row au-target"])[3]')),
        saveActivityButton: element(by.xpath('//button[contains(text(),"Save")]')),
        deleteActivityButton: element(by.xpath('//button[contains(text(),"Delete Activity")]')),
        deleteDialogInput: element(by.xpath('//input[@class="dialog-message__input au-target"]')),
        deleteDialogYesButton: element(by.xpath('//button[contains(text(),"Yes, I want to delete it")]')),
        columnDateSold: element(by.xpath('//a[text()="Date Sold"]')),
        unrealizedTab: element(by.xpath('//li[@class="au-target household-tax__header__menu__item"]')),
        realizedTab: element(by.xpath('//li[@class="au-target household-tax__header__menu__item"]')),
        yearDropdown: element(by.xpath('//div[@class="ab-dropdown__dropdown"]')),
        positionsGrid: element(by.xpath('//div[@class="k-grid k-widget k-display-block"]')),
        positionElem: element(by.xpath('//div[@class="k-grid-content k-auto-scrollable"]//tr[1]')),
        positionDetailsLabel: element(by.xpath('//div[@class="position-details__title"]')),
        taxMethodDropdown: element(by.xpath('//div[3]//ab-dropdown[1]')),
        taxMethodDropdownItem: element(by.xpath('//div[@class="ab-dropdown__content au-target"]//li[2]')),
        savePositionButton: element(by.xpath('//button[contains(text(),"Save")]')),
    }
};